In [3]:
import numpy
import pandas as pd
from geopy.distance import geodesic

In [4]:
fraud_test_df = pd.read_csv("../datas/fraudTest.csv")
fraud_train_df = pd.read_csv("../datas/fraudTrain.csv")

In [5]:
fraud_train_df.sample(5)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
455117,455117,2019-07-21 00:59:47,3593118134380341,"fraud_Bins, Balistreri and Beatty",shopping_pos,356.48,Laura,Casey,F,6114 Moran Way,...,44.4971,-67.9503,1131,Make,1959-05-10,6866532f5c219b1f3890e95e1779f554,1342832387,44.627284,-67.645965,0
20370,20370,2019-01-13 09:39:08,3559723917628303,"fraud_Swaniawski, Lowe and Robel",shopping_pos,141.64,Matthew,Huerta,M,622 Williams Trafficway,...,42.4048,-88.3054,928,Outdoor activities/education manager,1985-05-13,410ae3e93c37b70cb6a1631c326b2c57,1326447548,43.182182,-87.605634,0
93300,93300,2019-02-24 22:10:31,4186530744674,fraud_Jacobi Inc,health_fitness,38.88,Casey,Howell,F,374 Christopher Ramp Suite 855,...,33.3645,-81.2718,4913,Technical brewer,1966-11-10,ef2490941bcb6f8719a054713b7a08ff,1330121431,33.845690,-80.626397,0
1000211,1000211,2020-02-14 15:48:11,4005676619255478,fraud_Morissette LLC,entertainment,16.15,William,Perry,M,458 Phillips Island Apt. 768,...,30.4590,-90.9027,71335,Herbalist,1994-05-31,7faa49973f44a70d39ce7a9d051a7c3d,1360856891,29.943386,-90.169070,0
952723,952723,2020-01-17 19:21:14,501899453424,fraud_Hilpert-Conroy,kids_pets,128.96,Jessica,Dominguez,F,06393 Nancy Parkways Suite 855,...,33.9845,-85.9077,67082,Ceramics designer,1970-01-08,6c7cbaa1b8869bb54b2a7c5becea908b,1358450474,33.329449,-85.497360,0

In [6]:
fraud_train_df.shape

(1296675, 23)

In [7]:
fraud_train_df["is_fraud"].value_counts()

is_fraud
0    1289169
1       7506
Name: count, dtype: int64

In [8]:
fraud_test_df.isna().sum() / len(fraud_test_df) * 100

Unnamed: 0               0.0
trans_date_trans_time    0.0
cc_num                   0.0
merchant                 0.0
category                 0.0
amt                      0.0
first                    0.0
last                     0.0
gender                   0.0
street                   0.0
city                     0.0
state                    0.0
zip                      0.0
lat                      0.0
long                     0.0
city_pop                 0.0
job                      0.0
dob                      0.0
trans_num                0.0
unix_time                0.0
merch_lat                0.0
merch_long               0.0
is_fraud                 0.0
dtype: float64

In [9]:
fraud_train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [10]:
fraud_train_df["category"].value_counts()

category
gas_transport     131659
grocery_pos       123638
home              123115
shopping_pos      116672
kids_pets         113035
shopping_net       97543
entertainment      94014
food_dining        91461
personal_care      90758
health_fitness     85879
misc_pos           79655
misc_net           63287
grocery_net        45452
travel             40507
Name: count, dtype: int64

In [11]:
fraud_test_df["job"].value_counts()

job
Film/video editor                4119
Exhibition designer              3968
Surveyor, land/geomatics         3756
Naval architect                  3750
Designer, ceramics/pottery       3463
                                 ...
Estate manager/land agent         195
Engineer, civil (consulting)      194
Operational investment banker      11
Software engineer                  11
Engineer, water                     8
Name: count, Length: 478, dtype: int64

In [12]:
fraud_train_df["cc_num"].value_counts()

cc_num
571365235126           3123
4512828414983801773    3123
36722699017270         3119
213112402583773        3117
3545109339866548       3113
                       ...
180097223252063           7
4225628813173670          7
501894933032              7
4975457191020             7
340187018810220           7
Name: count, Length: 983, dtype: int64

In [13]:
fraud_train_df["state"].value_counts()

state
TX    94876
NY    83501
PA    79847
CA    56360
OH    46480
MI    46154
IL    43252
FL    42671
AL    40989
MO    38403
MN    31714
AR    31127
NC    30266
WI    29368
VA    29250
SC    29190
KY    28475
IN    27580
IA    26985
OK    26671
MD    26193
GA    26063
WV    25691
NJ    24603
NE    24168
KS    22996
MS    21188
LA    20965
WY    19322
WA    18924
OR    18597
TN    17554
ME    16505
NM    16407
ND    14786
CO    13880
MA    12376
SD    12324
VT    11768
MT    11754
AZ    10770
UT    10699
NH     8278
CT     7702
NV     5607
ID     5545
DC     3613
HI     2559
AK     2120
RI      550
DE        9
Name: count, dtype: int64

In [14]:
#drop colonnes innutiles
drop_cols = ["Unnamed: 0", "cc_num", "merchant", "first", "last", "street", "zip", "unix_time", "trans_num", "city"]
df_clean = fraud_train_df.drop(columns=drop_cols)

#age du consommateur
df_clean["dob"] = pd.to_datetime(df_clean["dob"])
df_clean["age"] = pd.Timestamp.now().year - df_clean["dob"].dt.year

df_clean = df_clean.drop(columns=["dob"])

#nombre de KM entre vendeur et consommateur
df_clean["distance_km"] = df_clean.apply(
    lambda row: int(geodesic(
        (row["lat"], row["long"]), 
        (row["merch_lat"], row["merch_long"])
    ).km), axis=1
)

drop_loc_cols = ["lat", "long", "merch_lat", "merch_long"]
df_clean = df_clean.drop(columns=drop_loc_cols)

In [15]:
df_clean["trans_date_trans_time"] = pd.to_datetime(df_clean["trans_date_trans_time"])

df_clean["hour"]  = df_clean["trans_date_trans_time"].dt.hour
df_clean["day"]   = df_clean["trans_date_trans_time"].dt.day
df_clean["month"] = df_clean["trans_date_trans_time"].dt.month
df_clean["year"]  = df_clean["trans_date_trans_time"].dt.year

df_clean = df_clean.drop(columns=["trans_date_trans_time"])

In [16]:
df_clean.head()

,category,amt,gender,state,city_pop,job,is_fraud,age,distance_km,hour,day,month,year
0,misc_net,4.97,F,NC,3495,"Psychologist, counselling",0,38,78,0,1,1,2019
1,grocery_pos,107.23,F,WA,149,Special educational needs teacher,0,48,30,0,1,1,2019
2,entertainment,220.11,M,ID,4154,Nature conservation officer,0,64,108,0,1,1,2019
3,gas_transport,45.00,M,MT,1939,Patent attorney,0,59,95,0,1,1,2019
4,misc_pos,41.96,M,VA,99,Dance movement psychotherapist,0,40,77,0,1,1,2019

In [17]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 13 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   category     1296675 non-null  object
 1   amt          1296675 non-null  float64
 2   gender       1296675 non-null  object
 3   state        1296675 non-null  object
 4   city_pop     1296675 non-null  int64
 5   job          1296675 non-null  object
 6   is_fraud     1296675 non-null  int64
 7   age          1296675 non-null  int64
 8   distance_km  1296675 non-null  int64
 9   hour         1296675 non-null  int32
 10  day          1296675 non-null  int32
 11  month        1296675 non-null  int32
 12  year         1296675 non-null  int32
dtypes: float64(1), int32(4), int64(4), object(4)
memory usage: 108.8+ MB

In [18]:
df_clean["job"].unique()

array(['Psychologist, counselling', 'Special educational needs teacher',
       'Nature conservation officer', 'Patent attorney',
       'Dance movement psychotherapist', 'Transport planner',
       'Arboriculturist', 'Designer, multimedia',
       'Public affairs consultant', 'Pathologist', 'IT trainer',
       'Systems developer', 'Engineer, land', 'Systems analyst',
       'Naval architect', 'Radiographer, diagnostic',
       'Programme researcher, broadcasting/film/video', 'Energy engineer',
       'Event organiser', 'Operational researcher', 'Market researcher',
       'Probation officer', 'Leisure centre manager',
       'Corporate investment banker', 'Therapist, occupational',
       'Call centre manager', 'Police officer',
       'Education officer, museum', 'Physiotherapist', 'Network engineer',
       'Forensic psychologist', 'Geochemist',
       'Armed forces training and education officer',
       'Designer, furniture', 'Optician, dispensing',
       'Psychologist, forensic', 'Librarian, public', 'Fine artist',
       'Scientist, research (maths)', 'Research officer, trade union',
       'Tourism officer', 'Human resources officer', 'Surveyor, minerals',
       'Applications developer', 'Video editor', 'Curator',
       'Research officer, political party', 'Engineer, mining',
       'Education officer, community', 'Physicist, medical',
       'Amenity horticulturist', 'Electrical engineer',
       'Television camera operator', 'Higher education careers adviser',
       'Ambulance person', 'Dealer', 'Paediatric nurse',
       'Trading standards officer', 'Engineer, technical sales',
       'Designer, jewellery', 'Clinical biochemist',
       'Engineer, electronics', 'Water engineer', 'Science writer',
       'Film/video editor', 'Solicitor, Scotland',
       'Product/process development scientist', 'Tree surgeon',
       'Careers information officer', 'Geologist, engineering',
       'Counsellor', 'Freight forwarder',
       'Senior tax professional/tax inspector',
       'Engineer, broadcasting (operations)',
       'English as a second language teacher', 'Economist',
       'Child psychotherapist', 'Claims inspector/assessor',
       'Tourist information centre manager',
       'Exhibitions officer, museum/gallery', 'Location manager',
       'Engineer, biomedical', 'Research scientist (physical sciences)',
       'Purchasing manager', 'Editor, magazine features',
       'Operations geologist', 'Interpreter', 'Engineering geologist',
       'Agricultural consultant', 'Paramedic', 'Financial adviser',
       'Administrator, education', 'Educational psychologist',
       'Financial trader', 'Audiological scientist',
       'Scientist, audiological',
       'Administrator, charities/voluntary organisations',
       'Health service manager', 'Retail merchandiser',
       'Telecommunications researcher', 'Exercise physiologist',
       'Accounting technician', 'Product designer',
       'Waste management officer', 'Mining engineer', 'Surgeon',
       'Therapist, horticultural', 'Environmental consultant',
       'Broadcast presenter', 'Producer, radio',
       'Engineer, communications',
       'Historic buildings inspector/conservation officer',
       'Teacher, English as a foreign language', 'Materials engineer',
       'Health visitor', 'Medical secretary', 'Theatre director',
       'Technical brewer', 'Land/geomatics surveyor',
       'Engineer, structural', 'Diagnostic radiographer',
       'Television production assistant', 'Medical sales representative',
       'Building control surveyor', 'Therapist, sports',
       'Structural engineer', 'Commercial/residential surveyor',
       'Database administrator', 'Exhibition designer',
       'Training and development officer', 'Mechanical engineer',
       'Medical physicist', 'Administrator', 'Mudlogger',
       'Fisheries officer', 'Conservator, museum/gallery',
       'Programmer, multimedia', 'Cytogeneticist',
       'Multimedia programmer', 'Counselling psychologist', 'Chiropodist',
       'Teacher, early years/pre', 'Cartographer', 'Pensions consultant',
       'Primary school teacher', 'Electronics engineer',
       'Museum/gallery exhibitions officer', 'Air broker',
       'Chemical engineer', 'Advertising account executive',
       'Advertising account planner',
       'Chartered legal executive (England and Wales)',
       'Psychiatric nurse', 'Secondary school teacher',
       'Librarian, academic', 'Embryologist, clinical', 'Immunologist',
       'Television floor manager', 'Contractor', 'Health physicist',
       'Copy', 'Bookseller', 'Land', 'Chartered loss adjuster',
       'Occupational psychologist', 'Facilities manager',
       'Further education lecturer', 'Archivist', 'Investment analyst',
       'Engineer, building services', 'Psychologist, sport and exercise',
       'Journalist, newspaper', 'Doctor, hospital', 'Phytotherapist',
       'Pharmacologist', 'Horticultural therapist', 'Hydrologist',
       'Community arts worker', 'Public house manager', 'Architect',
       'Lexicographer', 'Psychotherapist, child',
       'Teacher, secondary school', 'Toxicologist',
       'Commercial horticulturist', 'Podiatrist', 'Building surveyor',
       'Architectural technologist', 'Editor, film/video',
       'Social researcher', 'Wellsite geologist', 'Minerals surveyor',
       'Designer, ceramics/pottery', 'Mental health nurse',
       'Volunteer coordinator', 'Chief Technology Officer',
       'Camera operator', 'Copywriter, advertising', 'Surveyor, mining',
       'Product manager', "Nurse, children's", 'Pension scheme manager',
       'Archaeologist', 'Sub', 'Designer, interior/spatial',
       'Futures trader', 'Chief Financial Officer',
       'Museum education officer', 'Quantity surveyor',
       'Physiological scientist', 'Loss adjuster, chartered',
       'Pilot, airline', 'Production assistant, radio',
       'Immigration officer', 'Retail banker',
       'Health and safety adviser', 'Teacher, special educational needs',
       'Jewellery designer', 'Community pharmacist',
       'Control and instrumentation engineer', 'Make',
       'Early years teacher', 'Sales professional, IT',
       'Scientist, marine', 'Intelligence analyst',
       'Clinical research associate', 'Administrator, local government',
       'Barrister', 'Engineer, control and instrumentation',
       'Clothing/textile technologist', 'Development worker, community',
       'Art therapist', 'Sales executive',
       'Armed forces logistics/support/administrative officer',
       'Optometrist', 'Insurance underwriter', 'Charity officer',
       'Civil Service fast streamer', 'Retail buyer',
       'Magazine features editor', 'Equities trader',
       'Trade mark attorney', 'Research scientist (life sciences)',
       'Psychotherapist', 'Pharmacist, community', 'Risk analyst',
       'Engineer, maintenance', 'Logistics and distribution manager',
       'Water quality scientist', 'Lecturer, further education',
       'Production assistant, television', 'Tour manager',
       'Music therapist', 'Surveyor, land/geomatics',
       'Engineer, production', 'Acupuncturist', 'Hospital doctor',
       'Teacher, primary school', 'Accountant, chartered public finance',
       'Illustrator', 'Scientist, physiological', 'Buyer, industrial',
       'Scientist, research (physical sciences)', 'Radio producer',
       'Manufacturing engineer', 'Animal technologist',
       'Production engineer', 'Biochemist, clinical',
       'Engineer, manufacturing', 'Comptroller',
       'General practice doctor', 'Designer, industrial/product',
       'Prison officer', 'Merchandiser, retail', 'Engineer, drilling',
       'Engineer, petroleum', 'Cabin crew', 'Commissioning editor',
       'Accountant, chartered certified', 'Local government officer',
       'Professor Emeritus', 'Press sub',
       'Chartered public finance accountant', 'Writer',
       'Chief Executive Officer', 'Occupational hygienist',
       'Doctor, general practice', 'Community education officer',
       'Landscape architect', 'Occupational therapist',
       'Special effects artist', 'Civil engineer, contracting',
       "Barrister's clerk", 'Travel agency manager',
       'Associate Professor', 'Neurosurgeon', 'Plant breeder/geneticist',
       'Radio broadcast assistant', 'Field seismologist',
       'Industrial/product designer', 'Metallurgist',
       "Politician's assistant", 'Insurance claims handler',
       'Theme park manager', 'Gaffer', 'Chief Strategy Officer',
       'Heritage manager', 'Ceramics designer', 'Animator',
       'Oceanographer', 'Colour technologist', 'Engineer, agricultural',
       'Therapist, drama', 'Orthoptist', 'Learning mentor',
       'Arts development officer', 'Biomedical engineer',
       'Race relations officer', 'Therapist, music', 'Retail manager',
       'Furniture designer', 'Building services engineer',
       'Maintenance engineer', 'Aid worker', 'Editor, commissioning',
       'Private music teacher', 'Scientist, biomedical',
       'Public relations account executive', 'Dispensing optician',
       'Advice worker', 'Hydrographic surveyor', 'Geoscientist',
       'Environmental health practitioner', 'Learning disability nurse',
       'Chief Operating Officer', 'Scientific laboratory technician',
       'Records manager', 'Barista', 'Marketing executive',
       'Tax inspector', 'Musician', 'Therapist, art',
       'Engineer, automotive', 'Clinical psychologist', 'Warden/ranger',
       'Surveyor, rural practice', 'Sport and exercise psychologist',
       'Education administrator', 'Chief of Staff',
       'Nurse, mental health', 'Music tutor',
       'Planning and development surveyor',
       'Teaching laboratory technician', 'Chief Marketing Officer',
       'Theatre manager', 'Quarry manager',
       'Interior and spatial designer', 'Lecturer, higher education',
       'Regulatory affairs officer', 'Secretary/administrator',
       'Chemist, analytical', 'Designer, exhibition/display',
       'Pharmacist, hospital', 'Site engineer',
       'Equality and diversity officer', 'Public librarian',
       'Town planner', 'Chartered accountant', 'Programmer, applications',
       'Manufacturing systems engineer', 'Web designer',
       'Community development worker', 'Animal nutritionist',
       'Petroleum engineer', 'Information systems manager',
       'Press photographer', 'Insurance risk surveyor', 'Soil scientist',
       'Buyer, retail', 'Public relations officer',
       'Health promotion specialist', 'Psychiatrist',
       'Visual merchandiser', 'Rural practice surveyor', 'Hotel manager',
       'Communications engineer', 'Insurance broker',
       'Radiographer, therapeutic', 'Set designer', 'Tax adviser',
       'Drilling engineer', 'Fitness centre manager', 'Farm manager',
       'Management consultant', 'Energy manager',
       'Museum/gallery conservator', 'Herbalist', 'Osteopath',
       'Statistician', 'Hospital pharmacist', 'Estate manager/land agent',
       'Sports development officer', 'Investment banker, corporate',
       'Biomedical scientist', 'Television/film/video producer',
       'Nutritional therapist', 'Company secretary', 'Production manager',
       'Magazine journalist', 'Media buyer', 'Data scientist',
       'Engineer, civil (contracting)', 'Herpetologist',
       'Garment/textile technologist', 'Scientist, research (medical)',
       'Civil Service administrator', 'Airline pilot', 'Textile designer',
       'Environmental manager', 'Furniture conservator/restorer',
       'Horticultural consultant', 'Firefighter',
       'Geophysicist/field seismologist', 'Psychologist, clinical',
       'Development worker, international aid', 'Sports administrator',
       'IT consultant', 'Presenter, broadcasting',
       'Outdoor activities/education manager', 'Field trials officer',
       'Social research officer, government',
       'English as a foreign language teacher',
       'Restaurant manager, fast food', 'Hydrogeologist',
       'Research scientist (medical)', 'Designer, television/film set',
       'Geneticist, molecular', 'Designer, textile',
       'Licensed conveyancer', 'Emergency planning/management officer',
       'Geologist, wellsite', 'Air cabin crew', 'Seismic interpreter',
       'Surveyor, hydrographic', 'Charity fundraiser', 'Stage manager',
       'Aeronautical engineer', 'Glass blower/designer', 'Ecologist',
       'Horticulturist, commercial', 'Research scientist (maths)',
       'Engineer, aeronautical',
       'Conservation officer, historic buildings', 'Art gallery manager',
       'Advertising copywriter', 'Engineer, civil (consulting)',
       'Oncologist', 'Engineer, materials',
       'Scientist, clinical (histocompatibility and immunogenetics)',
       'Investment banker, operational', 'Medical technical officer',
       'Academic librarian', 'Artist', 'Clinical cytogeneticist',
       'TEFL teacher', 'Administrator, arts', 'Teacher, adult education',
       'Catering manager', 'Environmental education officer',
       'Conservator, furniture', 'Analytical chemist',
       'Broadcast engineer', 'Media planner', 'Lawyer',
       'Producer, television/film/video',
       'Armed forces technical officer', 'Engineer, site',
       'Contracting civil engineer', 'Veterinary surgeon',
       'Sales promotion account executive', 'Broadcast journalist',
       'Dancer', 'Forest/woodland manager', 'Personnel officer',
       'Industrial buyer', 'Accountant, chartered',
       'Air traffic controller', 'Careers adviser', 'Information officer',
       'Ship broker', 'Legal secretary', 'Homeopath', 'Solicitor',
       'Warehouse manager'], dtype=object)

In [19]:
df_clean["job"].nunique()

494

In [20]:
def categorize_job(job):
    job = job.lower()
    if any(w in job for w in ["engineer", "developer", "data", "software", "tech", "it", "programmer", "web", "seismic", "geophysic", "statistician", "cartographer"]):
        return "tech"
    elif any(w in job for w in ["health", "ambulance" "doctor", "nurse", "surgeon", "therapist", "medical", "paramedic", "radiograph", "optometrist", "chiropodist", "audiolog", "oncologist", "osteopath", "podiatrist", "pathologist", "immunologist", "physiologist", "toxicologist", "embryologist", "biochemist", "pharmacolog", "psychiatrist", "psychologist", "counsell", "optician", "herbalist", "acupuncturist", "orthoptist", "occupational hygienist", "clinical"]):
        return "health"
    elif any(w in job for w in ["teacher", "professor", "lecturer", "educator", "tutor", "librarian", "archivist", "education", "mentor", "learning"]):
        return "education"
    elif any(w in job for w in ["manager", "director", "officer", "executive", "ceo", "administrator", "coordinator", "comptroller", "company secretary", "chief of staff"]):
        return "management"
    elif any(w in job for w in ["accountant", "financial", "banker", "analyst", "tax", "insurance", "broker", "pensions", "economist", "futures trader", "dealer", "claims inspector", "loss adjuster"]):
        return "finance"
    elif any(w in job for w in ["driver", "delivery", "transport", "pilot", "freight", "air broker", "cabin crew", "air cabin"]):
        return "transport"
    elif any(w in job for w in ["designer", "artist", "musician", "journalist", "media", "broadcast", "photographer", "ceramics", "jewellery", "animator", "illustrator", "producer", "radio producer", "camera operator", "gaffer", "television", "curator", "conservator"]):
        return "creative"
    elif any(w in job for w in ["lawyer", "barrister", "legal", "conveyancer", "loss adjuster", "attorney", "patent", "trade mark"]):
        return "legal"
    elif any(w in job for w in ["scientist", "researcher", "geologist", "ecologist", "geneticist", "geochemist", "hydrogeologist", "archaeologist", "oceanographer", "hydrologist", "chemist", "metallurgist", "mudlogger"]):
        return "science"
    elif any(w in job for w in ["surveyor", "planner", "architect", "contractor", "building", "land"]):
        return "construction"
    elif any(w in job for w in ["consultant", "adviser", "advisor"]):
        return "consulting"
    elif any(w in job for w in ["firefighter", "police", "security", "military", "warden", "ranger"]):
        return "public_safety"
    elif any(w in job for w in ["farmer", "agricultural", "horticulturist", "arboriculturist"]):
        return "agriculture"
    elif any(w in job for w in ["buyer", "merchandiser", "retail", "bookseller", "barista", "dealer"]):
        return "commerce"
    elif any(w in job for w in ["aid worker", "development worker", "volunteer", "charity"]):
        return "social"
    elif any(w in job for w in ["sport", "exercise", "fitness"]):
        return "sport"
    else:
        return "other"


df_clean["customer_job_category"] = df_clean["job"].apply(categorize_job)
df_clean = df_clean.drop(columns=["job"])

In [21]:
df_clean["customer_job_category"].nunique()

16

In [22]:
df_clean["customer_job_category"].unique()

array(['health', 'education', 'management', 'legal', 'transport',
       'agriculture', 'creative', 'consulting', 'tech', 'finance',
       'other', 'science', 'construction', 'commerce', 'social',
       'public_safety'], dtype=object)

In [23]:
df_clean["customer_job_category"].value_counts()

customer_job_category
tech             378778
health           220187
management       163508
creative         106292
finance           89113
education         82286
science           76376
construction      53712
other             37014
legal             20455
consulting        18292
commerce          15953
transport         12806
public_safety      8649
agriculture        8185
social             5069
Name: count, dtype: int64

In [26]:
df_clean["category"].value_counts()

category
gas_transport     131659
grocery_pos       123638
home              123115
shopping_pos      116672
kids_pets         113035
shopping_net       97543
entertainment      94014
food_dining        91461
personal_care      90758
health_fitness     85879
misc_pos           79655
misc_net           63287
grocery_net        45452
travel             40507
Name: count, dtype: int64

In [24]:
df_clean.sample(25)

,category,amt,gender,state,city_pop,is_fraud,age,distance_km,hour,day,month,year,customer_job_category
837439,entertainment,57.13,F,AR,1383,0,27,106,21,12,12,2019,tech
555817,home,45.02,F,NY,1271,0,68,34,12,25,8,2019,creative
417957,misc_pos,2.32,M,AL,190178,0,53,51,15,7,7,2019,creative
2339,personal_care,50.55,F,MS,1923,0,66,116,23,1,1,2019,health
251793,kids_pets,93.96,F,GA,165556,0,29,104,19,5,5,2019,management
55292,food_dining,29.30,M,AL,8269,0,49,62,21,2,2,2019,construction
155702,entertainment,77.36,M,GA,782,0,44,34,12,24,3,2019,health
479464,gas_transport,59.71,F,NJ,2307,0,57,110,5,29,7,2019,tech
1212843,food_dining,9.77,M,CO,151815,0,38,82,13,22,5,2020,education
819123,personal_care,26.97,F,WV,3994,0,90,64,16,8,12,2019,health
244223,entertainment,131.20,F,PA,489,0,70,32,17,2,5,2019,management
1268626,grocery_pos,110.75,F,OH,338,0,38,99,0,11,6,2020,tech
305152,shopping_pos,122.06,F,SC,2408,0,29,110,22,27,5,2019,tech
24799,entertainment,102.59,M,IL,1656,0,57,77,8,15,1,2019,tech
463438,misc_net,6.33,F,NE,1745,0,53,77,10,23,7,2019,tech
652578,misc_net,4.03,M,CA,172817,0,44,87,11,5,10,2019,construction
1294470,shopping_net,35.16,F,WI,13973,0,45,96,17,20,6,2020,management
148454,grocery_pos,117.24,M,CA,123,0,53,78,9,21,3,2019,education
982774,entertainment,119.47,F,OH,321,0,47,20,15,3,2,2020,tech
311412,entertainment,55.32,M,MT,18182,0,51,72,22,30,5,2019,tech
754590,home,124.86,F,CA,92043,0,65,132,16,18,11,2019,tech
651297,personal_care,15.97,M,OH,128,0,80,38,21,4,10,2019,health
1272496,shopping_net,5.57,F,MI,6469,0,47,54,19,12,6,2020,legal
1278599,kids_pets,99.70,M,LA,68211,0,85,57,23,14,6,2020,tech
263433,gas_transport,47.37,F,AR,37,0,68,84,10,11,5,2019,education

In [25]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   category               1296675 non-null  object
 1   amt                    1296675 non-null  float64
 2   gender                 1296675 non-null  object
 3   state                  1296675 non-null  object
 4   city_pop               1296675 non-null  int64
 5   is_fraud               1296675 non-null  int64
 6   age                    1296675 non-null  int64
 7   distance_km            1296675 non-null  int64
 8   hour                   1296675 non-null  int32
 9   day                    1296675 non-null  int32
 10  month                  1296675 non-null  int32
 11  year                   1296675 non-null  int32
 12  customer_job_category  1296675 non-null  object
dtypes: float64(1), int32(4), int64(4), object(4)
memory usage: 108.8+ MB