In [5]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import pandas as pd
import requests
from src.pipeline.clean_datas import clean_datas_history

In [6]:
base_url = "https://sdacelo-real-time-fraud-detection.hf.space"
transaction_url = f"{base_url}/current-transactions"

response = requests.get(transaction_url)
data = response.json()

df = pd.read_json(data, orient="split")
df

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_10135/3322609588.py:7: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient="split")

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud,current_time
376990,4079773899158,fraud_Marvin-Lind,personal_care,135.06,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,ID,...,44.6255,-116.4493,129,Cartographer,1965-12-15,04c3c27d92ba360aae151cc7c620b88a,45.491023,-115.613774,0,2026-03-08 16:40:37.772

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 376990 to 376990
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cc_num        1 non-null      int64
 1   merchant      1 non-null      object
 2   category      1 non-null      object
 3   amt           1 non-null      float64
 4   first         1 non-null      object
 5   last          1 non-null      object
 6   gender        1 non-null      object
 7   street        1 non-null      object
 8   city          1 non-null      object
 9   state         1 non-null      object
 10  zip           1 non-null      int64
 11  lat           1 non-null      float64
 12  long          1 non-null      float64
 13  city_pop      1 non-null      int64
 14  job           1 non-null      object
 15  dob           1 non-null      object
 16  trans_num     1 non-null      object
 17  merch_lat     1 non-null      float64
 18  merch_long    1 non-null      float64
 19  is_fraud      1 non-null      int64
 20  current_time  1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(4), object(11)
memory usage: 176.0+ bytes

In [8]:
df_clean = clean_datas_history(df, "api")
df_clean

,category,amt,gender,state,city_pop,is_fraud,current_time,trans_hour,trans_day,trans_month,age,distance_km,customer_job_category
376990,personal_care,135.06,M,ID,129,0,2026-03-08 16:40:37.772,16,8,3,61,116,tech