In [7]:
import sys
import os
sys.path.append(os.path.abspath(".."))

import pandas as pd
import requests
from src.pipeline.clean_datas import clean_datas_history

In [8]:
base_url = "https://sdacelo-real-time-fraud-detection.hf.space"
transaction_url = f"{base_url}/current-transactions"

response = requests.get(transaction_url)
data = response.json()

df = pd.read_json(data, orient="split")
df

/var/folders/xs/9pw_49kx273dmym0qk_0l_s00000gn/T/ipykernel_74460/3322609588.py:7: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient="split")

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud,current_time
110572,2712209726293386,"fraud_Goyette, Howell and Collier",shopping_pos,214.31,Jenna,Brooks,F,50872 Alex Plain Suite 088,Baton Rouge,LA,...,30.4066,-91.1468,378909,"Designer, furniture",1977-02-22,1d741c06d28df9d98086abd1c6e23816,30.48082,-90.455017,0,2026-03-14 08:33:25.772

In [9]:
df.to_json(orient='records')

'[{"cc_num":2712209726293386,"merchant":"fraud_Goyette, Howell and Collier","category":"shopping_pos","amt":214.31,"first":"Jenna","last":"Brooks","gender":"F","street":"50872 Alex Plain Suite 088","city":"Baton Rouge","state":"LA","zip":70808,"lat":30.4066,"long":-91.1468,"city_pop":378909,"job":"Designer, furniture","dob":"1977-02-22","trans_num":"1d741c06d28df9d98086abd1c6e23816","merch_lat":30.48082,"merch_long":-90.455017,"is_fraud":0,"current_time":1773477205772}]'

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1 entries, 185357 to 185357
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cc_num        1 non-null      int64
 1   merchant      1 non-null      object
 2   category      1 non-null      object
 3   amt           1 non-null      float64
 4   first         1 non-null      object
 5   last          1 non-null      object
 6   gender        1 non-null      object
 7   street        1 non-null      object
 8   city          1 non-null      object
 9   state         1 non-null      object
 10  zip           1 non-null      int64
 11  lat           1 non-null      float64
 12  long          1 non-null      float64
 13  city_pop      1 non-null      int64
 14  job           1 non-null      object
 15  dob           1 non-null      object
 16  trans_num     1 non-null      object
 17  merch_lat     1 non-null      float64
 18  merch_long    1 non-null      float64
 19  is_fraud      1 non-null      int64
 20  current_time  1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(4), object(11)
memory usage: 176.0+ bytes

In [4]:
df_clean = clean_datas_history(df, "api")
df_clean

,category,amt,gender,state,city_pop,is_fraud,current_time,trans_hour,trans_day,trans_month,age,distance_km,customer_job_category
185357,gas_transport,72.2,F,WV,630,0,2026-03-13 18:58:03.126,18,13,3,67,93,creative

In [ ]:
import json
from dotenv import load_dotenv
load_dotenv("../.env")

from libs.S3.s3 import s3_client

obj = s3_client().get_object(
    Bucket="jedha-fraud-detection-qha",
    Key="realtime_transactions/20260314_144506.json"
)
transaction = json.loads(obj['Body'].read().decode('utf-8'))
transaction

In [ ]:
transaction